### ISSUE TITLE
queues: priority for some members

### ISSUE THREAD

**Issue by benfitzpatrick** [cylc/cylc#1882] opened 2016-06-10 09:16 UTC
It might be nice to have extra syntax to allow prioritisation of some families or tasks within a queue.

Something like:
```ini
[scheduling]
    [[queues]]
        limit = 5
        members = FOO, BARBAZ
        priorities = BARBAZ, FOO
```

You can arguably achieve a similar thing with multiple queues, but it isn't quite as flexible. It should just be a slight sorting change in task_pool.

One more step on the road to making cylc a scheduler!

**Comment by matthewrmshin** [comment] 2016-06-10 09:21
This appears to be a duplicate of #1196.

**Closed by matthewrmshin** 2016-06-10 09:21 UTC

**Comment by benfitzpatrick** [comment] 2016-06-10 09:48
Hah, great.
