### ISSUE TITLE
cylc validate: misinterpreting date as offset?

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1951] opened 2016-07-25 10:59 UTC
If you write a suite as follows:

```
[cylc]
    UTC mode = True
[scheduling]
    initial cycle point = 20100101T0000Z
    final cycle point   = +P1D
[[dependencies]]
    [[[R1]]]
        graph = init_cycle

    [[[R1/20100101T0600Z]]]
        graph = fixed_cycle

    [[[T12]]]
        graph = fixed_cycle[20100101T0600] => foo

[runtime]
    [[foo, fixed_cycle, init_cycle]]
        script = true
```

validation seems to run forever, chewing through cpu and memory, eventually failing with:

```
Instantiating tasks to check trigger expressions
  + foo.20100101T1200Z ok
Cannot dump TimePoint year: 10000 not in bounds 0 to 9999.
Traceback (most recent call last):
  File ".../cylc/bin/cylc-validate", line 124, in <module>
    main()
  File ".../cylc/bin/cylc-validate", line 90, in main
    'ERROR, failed to instantiate task %s' % name)
cylc.config.SuiteConfigError: 'ERROR, failed to instantiate task fixed_cycle'
```

Best guess is that its reading the date in the fixed_cycle[XX] as some sort of offset.

While `PCCYYMMDDTHHMM` should be supported either `CCYYMMDDTHHMM` should be being read as a specific cycle point (similar to foo[^] being expanded out to foo[initial_cycle_point]) or rejected as not being an offset.

**Comment by arjclark** [comment] 2016-12-09 15:23
@benfitzpatrick - as ISO syntax wizard, shall we just go for rejecting it as the initial behaviour?

**Comment by hjoliver** [comment] 2016-12-12 00:34
@arjclark - I'm not entirely sure what you mean by "rejecting it as the initial behaviour"? - presumably we should support the intended behaviour in the example above, it seems pretty sensible.

**Comment by arjclark** [comment] 2016-12-12 08:07
@hjoliver - I'm asking should we just implement the reject what appears to be an invalid offset, leaving specific date based triggering as a low priority enhancement for another time?

**Comment by hjoliver** [comment] 2016-12-12 08:24
@arjclark - ok, that's fine.

**Comment by hjoliver** [comment] 2016-12-16 04:04
Closing as duplicate of #1394

**Closed by hjoliver** 2016-12-16 04:04 UTC
Labels: bug, duplicate
