### ISSUE TITLE
Add confirmation for a cold restart when running from cylc gui

### ISSUE THREAD

**Issue by malcolmbrooks** [cylc/cylc#1971] opened 2016-08-24 09:44 UTC
When restarting a stopped suite from the gcylc gui (from the 'Control', 'Run Suite' options) it is currently far too easy to select a cold start when a restart is what is needed.

In particular, this is very easy to make this mistake when running a large number of suites and these experience common failures due to disk outages/timeouts etc. Large suites might have used up a considerable amount of compute resources to get to their current state, and an accidental cold-restart effectively deletes this work.

Please could the 'cold restart' option pop up a confirmation dialogue asking the use if they are sure they want to do a cold restart.

Just restarting a suite should not pop up a dialogue, so that users do not get into the habit of clicking a dialogue on restart without thinking about it.

If, for some reason, it is thought that some users have different working practices and frequently do cold starts and would not want this feature, then could it be disabled with a preference setting.

**Comment by matthewrmshin** [comment] 2016-08-24 10:12
I think this is a duplicate of #1030.

**Closed by matthewrmshin** 2016-08-24 10:12 UTC
Labels: duplicate
