### ISSUE TITLE
Some Gnome-3 equivalent of the cylc gnome-2 panel app. 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#570] opened 2013-07-10 06:21 UTC
See:
- https://github.com/cylc/cylc/issues/79#issuecomment-13921932
- https://github.com/cylc/cylc/issues/79#issuecomment-13935341

**Comment by hjoliver** [comment] 2016-06-19 16:01
[meeting] - no hurry on this, but it may need to be addressed before RHEL7 is deployed at the MO.

**Comment by matthewrmshin** [comment] 2017-06-22 19:56
Marked as a duplicate of #112.

**Closed by matthewrmshin** 2017-06-22 19:56 UTC
