### ISSUE TITLE
Configurable job log viewer command per batch system per host

### ISSUE THREAD

**Issue by matthewrmshin** [cylc/cylc#1588] opened 2015-09-02 13:47 UTC
For example, PBS is configured to use a holding area for writing job out/err files while the job is running, and only copy the out/err files to the specified location when the job completes. Local system administrators have developed commands for users to retrieve and print the contents of the out/err files while the job is running. (E.g. `qcat -o|-e JOB-ID`.)

It should be possible for `cylc cat-log` and `cylc gui` to take advantage of this kind of commands, but we'll need to be able to site global configure the command for job hosts with the relevant batch systems.

**Comment by benfitzpatrick** [comment] 2015-09-02 13:50
Duplicate of #1513!

**Closed** 2015-09-22 09:58 UTC
