### ISSUE TITLE
cylc gcylc: filter option in gcylc.rc

### ISSUE THREAD

**Issue by kaday** [cylc/cylc#1619] opened 2015-09-24 10:18 UTC
User request for a `filter on` option in gcylc.rc so that when the gcylc GUI opens it filters the tasks, for example not showing the `succeeded` tasks.

**Comment by oliver-sanders** [comment] 2016-05-16 14:12
Closed by #1701?

**Comment by matthewrmshin** [comment] 2016-05-16 14:25
Closed by #1833.

**Closed by matthewrmshin** 2016-05-16 14:25 UTC
Labels: priority low

**Comment by matthewrmshin** [comment] 2016-05-16 14:26
#1701 is in fact a duplicate of this.
