### ISSUE TITLE
cylc cyclepoint - no longer working for datetime strings without a "T"?

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#2140] opened 2017-02-02 14:13 UTC
@matthewrmshin, @dpmatthews - raising as requested. Change in behaviour as follows:
```
> CYLC_VERSION=6.10.2 cylc cyclepoint 1993042500 --template='YYYY,MM,DD,HH,00,00'
1993,04,25,00,00,00
```
now not working as:
```
> CYLC_VERSION=7.1.0 cylc cyclepoint 1993042500 --template='YYYY,MM,DD,HH,00,00'
Usage: cylc [util] cycle-point [OPTIONS] [POINT]
...
cylc-cycle-point: error: ERROR: invalid cycle: Invalid ISO 8601 date representation: 1993042500
```
However, based on this:
```
> CYLC_VERSION=6.11.4 cylc cyclepoint 1993042500 --template='YYYY,MM,DD,HH,00,00'
WARNING: pre cylc 6 syntax is deprecated: non-ISO-8601-compatible cycle point: 1993042500
1993,04,25,00,00,00
```
I believe this change in behaviour is **deliberate**.

**Comment by matthewrmshin** [comment] 2017-02-02 15:11
I think this is definitely deliberate, and not a bug. Any reason why the pre cylc 6 10-digit syntax is still used? Alternatively, can `rose date` be used instead? Unless there is some strong feeling about fixing this, I'll close it down.

**Comment by arjclark** [comment] 2017-02-02 15:21
I'll have to find out *why* its done that way.

As I said earlier though, this does need highlighting to the userbase as it's a non-obvious change migrating between opsuite versions.

**Comment by matthewrmshin** [comment] 2017-02-02 15:28
Is this not covered under the heading *Removed deprecated cylc-5 syntax and features* (which the 10-digit date-time syntax is one of)?

**Comment by arjclark** [comment] 2017-02-02 15:34
Agreed, in the release notes its there, so this is as superfluous as an issue. However, at our site level it probably needs highlighting better - hence preferring to talk to you originally about mentioning at next PS checkpoint rather than raise an issue. I imagine this will catch out a few climate suites too...

**Closed** 2017-02-02 15:34 UTC
Labels: invalid
