### ISSUE TITLE
absolute paths for batch system job log directives

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc#1977] opened 2016-09-06 02:45 UTC
From @ScottWales - 

> It would be nice to have absolute paths to the output directory for the use case of manually running a task for testing. PBS evaluates output paths relative to the submit directory, not $HOME, so if you manually run a task from the Cylc log directory the output gets lost to the ether. Instead you need to submit the jobs while in your home directory.

> At our site at least PBSpro does not evaluate environment variables or ~'s in the output path, but perhaps a configuration option for a prefix to the output path could be added, which users could set to their home directory path. Alternately the home directory could be left to the shell to evaluate, e.g. `pbs -o $HOME/cylc-run/.../job.out $HOME/cylc-run/.../job`

**Comment by hjoliver** [comment] 2016-09-06 06:22
We could do a quick ssh to each task host at suite start-up to determine the home directory path on that host.

**Comment by matthewrmshin** [comment] 2016-09-06 07:48
We can probably determine where HOME is on a remote task host at the same time when we create the remote suite run directory hierarchy. A simple `pwd`should do the trick here. (Logic in `cylc.job_host`.)

**Comment by matthewrmshin** [comment] 2016-09-06 09:32
Having said that, if you want to manually submit the job file, you will probably want to edit it any way, e.g. to remove `cylc message` calls and other stuffs. At the same time, one can easily modify or remove the header's `-o` and `-e` settings.

In addition, I believe that the frequency of usage for manually submitting a job file would be very small.

So although this issue is seemingly easy to fix, I cannot see any point in introducing the functionality to cylc. (No doubt we'll end up introducing complex logic to handle unforeseen garbage output from SSH when we try to capture the output from `pwd` or `echo "$HOME"`.)

@hjoliver @ScottWales If I don't hear any objection, I'll close this down as *wontfix*.

**Comment by hjoliver** [comment] 2016-09-06 10:37
@matthewrmshin - I would agree with you **if** it's true that determining remote home path could be difficult due to "unforeseen output" from the ssh process.  Otherwise I think this would be useful.  It's not unusual for me to run job files manually when diagnosing problems, and it would be nice if this just worked without requiring our insider knowledge (job file path directives, how to disable messages, other?). To avoid spurious output from the user's `.bashrc` we could do `ssh 'echo XXX${HOME}'` (or similar) and filter for `XXX`.  Is there any other way of getting spurious output from such a simple ssh command?   Your point on other edits being required is true, but we could easily solve that too.  At the moment, you can edit `CYLC_MODE` from `scheduler` to `raw` to make `cylc message` just print to stdout instead of attempting to communicate with a suite daemon.  We could have `cylc jobs-submit` set that variable instead of hardwiring it, so that a manual run would automatically default to just printing messages.

**Comment by matthewrmshin** [comment] 2016-09-06 11:40
(@hjoliver These days I would never imagine submitting a job outside of a cylc suite - insider knowledge or not!)

**Comment by hjoliver** [comment] 2016-09-06 11:48
Maybe you're right ... I can't actually think of a good reason why users, as opposed to cylc developers, should need to do manually run job scripts (I was mostly messing about with cylc when doing this in the past).

**Comment by ScottWales** [comment] 2016-09-09 01:57
My main use would be to do quick test jobs to reproduce issues, without having to swap over to the UI server to resubmit, or to easily modify the jobs script to make sure correct modules are being loaded (is there a quick way to edit a Rose job so that changes are reflected in the running suite, rather than killing and restarting?). Not something that happens a lot, but handy to have.

**Comment by hjoliver** [comment] 2016-09-09 02:25
@ScottWales - are you aware of cylc "edit runs"?  GUI right-click -> "Trigger (edit run)" or CLI `cylc trigger --edit SUITE TASK_ID(s)`.   Before the task job submits, the newly-generated job script will pop up in your text editor, and the job will submit (after prompting) when you save it and exit.   This allows the entire job script to be modified at will, on the fly (not rose task app configurations though).

**Comment by matthewrmshin** [comment] 2016-09-09 08:08
You can use cylc's edit-run to edit the command line to `rose task-run` as well. E.g.:

```sh
# Add/Modify an environment variable
rose task-run --define='[env]FOO=foo'
# Unset an environment variable
rose task-run --define='[env]!FOO'
```

**Comment by matthewrmshin** [comment] 2016-09-15 07:56
Looks like the main use cases can all be solved by current functionality. Therefore, I am closing this down as *wontfix*. Please re-open if new use cases are found to justify development.

**Closed by matthewrmshin** 2016-09-15 07:56 UTC
Labels: small
