### ISSUE TITLE
'command output' windows are annoying

### ISSUE THREAD

**Issue by jonnyhtw** [cylc/cylc#2510] opened 2017-12-12 22:03 UTC
Hi there

In GCylc, is there a way to stop the proliferation of 'command output files' when (for example) opening a log file in the 'view in editor' option on right clicking on a task (e.g. see attached)? I'm not sure if they should close automatically but they never do for me.

Thanks 😄 

![foo](https://user-images.githubusercontent.com/12940715/33910910-4616a238-dff5-11e7-981b-6aa38219649d.png)

**Comment by hjoliver** [comment] 2017-12-12 23:20
Hi @jonnyhtw - those windows are there to capture and stdout/stderr generated by the "external command" being executed - in this case your edit session.  But I agree they're annoying, and usually not needed.  We should replace them with a dialog box that only pops up at the end only if any output is detected.  I presume they do close correctly if you hit the "close" button or kill them?

**Comment by jonnyhtw** [comment] 2017-12-12 23:24
Thanks for the additional info @hjoliver. Yes they always close as expected but the nature of the work I do means I end up with loads of them open a lot of the time. Not at all a priority but something to bear in mind I guess.

Thanks

Jonny

**Comment by hjoliver** [comment] 2017-12-13 01:49
Had a feeling we'd been here before!  Closing this as as a duplicate of #1671

**Comment by hjoliver** [comment] 2017-12-13 01:50
However, I will take a look soon-ish in case it's a very easy change to make...

**Closed** 2017-12-13 01:50 UTC
Labels: duplicate

**Comment by jonnyhtw** [comment] 2017-12-13 01:57
Ah OK, got it, thanks!

Jonny
