### ISSUE TITLE
Port to GTK3

### ISSUE THREAD

**Issue by amckinstry** [cylc/cylc#2540] opened 2018-01-15 08:45 UTC
Hi,

I'm the maintainer of Cylc in Debian/Ubuntu. We are planning to move to GTK3 this cycle (over the next 12-18 months) and hence drop pygtk support, which cylc uses.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885371
Are there plans to move cylc forward to GTK3/GObject?

thanks
Alastair McKinstry

**Comment by matthewrmshin** [comment] 2018-01-15 09:17
Close as this is a duplicate of #112. See discussion in #1873, which supersedes #112.

**Closed by matthewrmshin** 2018-01-15 09:17 UTC

**Comment by hjoliver** [comment] 2018-01-18 09:57
@amckinstry - thanks for the heads up on this; it does at least raise the urgency of our web GUI plans.

**Comment by hjoliver** [comment] 2019-03-14 23:57
@amckinstry - if you're still out there - and in case it's not obvious, the Cylc repository master branch is now at Python 3 with the old PyGTK GUI deleted.  Cylc-8, with a web UI, will not be released till late this year though.  In the meantime, several further cylc-7.8.x maintenance releases will be made, still with Python 2 and GTK.
