### ISSUE TITLE
Additive clock-triggered entries

### ISSUE THREAD

**Issue by arjclark** [cylc/cylc#1734] opened 2016-02-15 10:07 UTC
In some suites we've seen it'd be useful to be able to define clock-triggered entries in an additive manner (as we do for graphing sections).

This is particularly useful for suites where graphing sections are brought in from include files as it would mean we could keep all the graphing related entries in one place rather than in the "master" suite.rc file with various switches etc.

i.e. we should be able to do this:
suite.rc.processed:
```
# main suite.rc
[scheduling]
[[special tasks]]
  clock-triggered = foo
...
# main model graphing
...

# included sub-model.rc file
[scheduling]
[[special tasks]]
  clock-triggered = bar
```

#1364 relates as a by-product of being able to put this sort of thing in graphing.

**Comment by hjoliver** [comment] 2016-02-15 10:16
@arjclark - this is really a duplicate of #1363

**Comment by arjclark** [comment] 2016-02-15 10:18
D'oh - just went through all the issues and missed that one!

I'll close this and append the above to the end of that ticket.

**Closed** 2016-02-15 10:20 UTC
Labels: duplicate
